import Head from 'next/head'
import '@/styles/globals.css'

import { Header } from '@/components/Header'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Kevin Stewart-Mercurio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </>
  )
}
